import React from "react";
import { Search, Select, StandOut } from "../images";

const Features = () => {
  const featureList = [
    {
      name: "Search",
      image: Search,
      description:
        "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
    },
    {
      name: "Select",
      image: Select,
      description:
        "Choose from thousands of options generated by the slogan maker that fit your needs.",
    },
    {
      name: "Stand Out",
      image: StandOut,
      description: "Congrats on your new slogan. It's time to win the world!",
    },
  ];
  return (
    <div className="section-features">
      <div className="container">
        <div className="features-wrapper">
          {featureList.map(({ name, image, description }) => {
            return (
              <div className="feature-item">
                <img src={image} loading="lazy" alt="" />
                <h4>{name}</h4>
                <p>{description}</p>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default Features;
